apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gogs-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
#  - events
  - configmaps
  - secrets
  - routes
  verbs:
  - "create"
  - "update"
  - "delete"
  - "get"
  - "list"
  - "watch"
  - "patch"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "create"
  - "update"
  - "delete"
  - "get"
  - "list"
  - "watch"
  - "patch"
  # Enable this if operator-metering is installed in your cluster.
  #- apiGroups:
  #- monitoring.coreos.com
  #resources:
  #- servicemonitors
  #verbs:
  #- "get"
  #- "create"
- apiGroups:
  - gogs.opentlc.com
  resources:
  - '*'
  verbs:
  - "create"
  - "update"
  - "delete"
  - "get"
  - "list"
  - "watch"
  - "patch"
